-- MySQL Script generated by MySQL Workbench
-- Thu Feb 17 15:10:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Remessa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Remessa` (
  `idRemessa` INT NOT NULL,
  `totalInfracoes` INT NULL,
  `situacao` VARCHAR(45) NULL,
  PRIMARY KEY (`idRemessa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Infracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Infracao` (
  `idInfracao` INT NOT NULL,
  `dataInfracao` DATETIME NULL,
  `equipamento` VARCHAR(45) NULL,
  `velocidadePermitida` INT NULL,
  `velocidadeMedida` INT NULL,
  `valorBinario` BIT NULL,
  `Remessa_idRemessa` INT NOT NULL,
  PRIMARY KEY (`idInfracao`),
  INDEX `fk_Infracao_Remessa_idx` (`Remessa_idRemessa` ASC) VISIBLE,
  CONSTRAINT `fk_Infracao_Remessa`
    FOREIGN KEY (`Remessa_idRemessa`)
    REFERENCES `mydb`.`Remessa` (`idRemessa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;